#!/bin/bash

#########################################################
##
##  ask start up script for UNIX
##
#########################################################

# BIN_PATH='Users/kevin/Documents/git/AndroidStarterKit/'
BIN_PATH='/Users/kevin/Documents/git/AndroidStarterKit/ask-app/com.androidstarterkit.build/classes/main'
cd $BIN_PATH
java com.androidstarterkit.Ask $@

